import { AI_CHAT_COMPLETE_COMMAND, AI_OPENAI_OAUTH_AUTHORIZE_COMMAND, AI_OPENAI_OAUTH_EXCHANGE_CODE_COMMAND } from "./manager";

export const commands = [AI_CHAT_COMPLETE_COMMAND, AI_OPENAI_OAUTH_AUTHORIZE_COMMAND, AI_OPENAI_OAUTH_EXCHANGE_CODE_COMMAND];
