import { AI_COMPLETED_EVENT, AI_OPENAI_OAUTH_CONNECTED_EVENT, AI_PROVIDER_CONFIGURED_EVENT } from "./manager";

export const events = [AI_PROVIDER_CONFIGURED_EVENT, AI_OPENAI_OAUTH_CONNECTED_EVENT, AI_COMPLETED_EVENT];
