import { createHash } from "node:crypto";

export const DOCUMENT_EXPORT_WARNING_TEXT = "Local export only. Human review required before upload, email, submission, or external use.";

export type ResumeExportFormat = "markdown" | "docx";

export interface ResumeExportSection {
  title: string;
  bullets: string[];
}

export interface ResumeExportDraft {
  id: string;
  templateName?: string;
  sections: ResumeExportSection[];
  reviewChecklist?: Array<{ label: string; status?: string; detail?: string }>;
  sourceFacts?: string[];
  warnings?: string[];
}

export interface ResumeExportArtifact {
  format: ResumeExportFormat;
  filename: string;
  mimeType: string;
  bytes: Buffer;
  textContent: string;
  checksum: string;
  byteLength: number;
  warningText: string;
}

const DOCX_MIME_TYPE = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
const MARKDOWN_MIME_TYPE = "text/markdown; charset=utf-8";

function safeFilenamePart(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 80) || "resume";
}

function markdownEscape(value: string) {
  return value.replace(/\r\n/g, "\n").trim();
}

function xmlEscape(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function normalizeBullet(value: string) {
  return value.replace(/\s+/g, " ").trim();
}

function normalizeSections(draft: ResumeExportDraft) {
  return draft.sections
    .map((section) => ({ title: section.title.trim(), bullets: section.bullets.map(normalizeBullet).filter(Boolean) }))
    .filter((section) => section.title && section.bullets.length > 0);
}

export function renderResumeMarkdown(draft: ResumeExportDraft) {
  const sections = normalizeSections(draft);
  return [
    "# Resume Draft",
    draft.templateName ? `Template: ${markdownEscape(draft.templateName)}` : undefined,
    DOCUMENT_EXPORT_WARNING_TEXT,
    "",
    ...sections.flatMap((section) => [`## ${markdownEscape(section.title)}`, ...section.bullets.map((bullet) => `- ${markdownEscape(bullet)}`), ""]),
    "## Human Review",
    "- Confirm every claim before external use.",
    "- Compare this export against verified Profile Facts before upload, email, submission, or external use.",
    "",
    "Generated by Career OS for local review only."
  ].filter((line): line is string => typeof line === "string").join("\n");
}

const crcTable = Array.from({ length: 256 }, (_, index) => {
  let crc = index;
  for (let bit = 0; bit < 8; bit += 1) crc = (crc & 1) ? (0xedb88320 ^ (crc >>> 1)) : (crc >>> 1);
  return crc >>> 0;
});

function crc32(buffer: Buffer) {
  let crc = 0xffffffff;
  for (const byte of buffer) crc = crcTable[(crc ^ byte) & 0xff] ^ (crc >>> 8);
  return (crc ^ 0xffffffff) >>> 0;
}

function fixedDosDateTime() {
  return { dosTime: 0, dosDate: (1 << 5) | 1 };
}

function createZip(files: Array<{ path: string; content: string | Buffer }>) {
  const localParts: Buffer[] = [];
  const centralParts: Buffer[] = [];
  let offset = 0;
  const { dosTime, dosDate } = fixedDosDateTime();

  for (const file of files) {
    const name = Buffer.from(file.path, "utf8");
    const content = Buffer.isBuffer(file.content) ? file.content : Buffer.from(file.content, "utf8");
    const crc = crc32(content);
    const localHeader = Buffer.alloc(30);
    localHeader.writeUInt32LE(0x04034b50, 0);
    localHeader.writeUInt16LE(20, 4);
    localHeader.writeUInt16LE(0, 6);
    localHeader.writeUInt16LE(0, 8);
    localHeader.writeUInt16LE(dosTime, 10);
    localHeader.writeUInt16LE(dosDate, 12);
    localHeader.writeUInt32LE(crc, 14);
    localHeader.writeUInt32LE(content.length, 18);
    localHeader.writeUInt32LE(content.length, 22);
    localHeader.writeUInt16LE(name.length, 26);
    localHeader.writeUInt16LE(0, 28);
    localParts.push(localHeader, name, content);

    const centralHeader = Buffer.alloc(46);
    centralHeader.writeUInt32LE(0x02014b50, 0);
    centralHeader.writeUInt16LE(20, 4);
    centralHeader.writeUInt16LE(20, 6);
    centralHeader.writeUInt16LE(0, 8);
    centralHeader.writeUInt16LE(0, 10);
    centralHeader.writeUInt16LE(dosTime, 12);
    centralHeader.writeUInt16LE(dosDate, 14);
    centralHeader.writeUInt32LE(crc, 16);
    centralHeader.writeUInt32LE(content.length, 20);
    centralHeader.writeUInt32LE(content.length, 24);
    centralHeader.writeUInt16LE(name.length, 28);
    centralHeader.writeUInt16LE(0, 30);
    centralHeader.writeUInt16LE(0, 32);
    centralHeader.writeUInt16LE(0, 34);
    centralHeader.writeUInt16LE(0, 36);
    centralHeader.writeUInt32LE(0, 38);
    centralHeader.writeUInt32LE(offset, 42);
    centralParts.push(centralHeader, name);

    offset += localHeader.length + name.length + content.length;
  }

  const centralDirectory = Buffer.concat(centralParts);
  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(0, 4);
  end.writeUInt16LE(0, 6);
  end.writeUInt16LE(files.length, 8);
  end.writeUInt16LE(files.length, 10);
  end.writeUInt32LE(centralDirectory.length, 12);
  end.writeUInt32LE(offset, 16);
  end.writeUInt16LE(0, 20);

  return Buffer.concat([...localParts, centralDirectory, end]);
}

function paragraph(text: string) {
  return `<w:p><w:r><w:t xml:space="preserve">${xmlEscape(text)}</w:t></w:r></w:p>`;
}

function renderDocxDocumentXml(draft: ResumeExportDraft) {
  const sections = normalizeSections(draft);
  const paragraphs = [
    paragraph("Resume Draft"),
    draft.templateName ? paragraph(`Template: ${draft.templateName}`) : undefined,
    paragraph(DOCUMENT_EXPORT_WARNING_TEXT),
    ...sections.flatMap((section) => [paragraph(section.title), ...section.bullets.map((bullet) => paragraph(`• ${bullet}`))]),
    paragraph("Human Review"),
    paragraph("• Confirm every claim before external use."),
    paragraph("• Compare this export against verified Profile Facts before upload, email, submission, or external use."),
    paragraph("Generated by Career OS for local review only.")
  ].filter((item): item is string => Boolean(item));

  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${paragraphs.join("")}<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="720" w:right="720" w:bottom="720" w:left="720" w:header="0" w:footer="0" w:gutter="0"/></w:sectPr></w:body></w:document>`;
}

export function renderResumeDocx(draft: ResumeExportDraft) {
  const documentXml = renderDocxDocumentXml(draft);
  return createZip([
    {
      path: "[Content_Types].xml",
      content: `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>`
    },
    {
      path: "_rels/.rels",
      content: `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`
    },
    { path: "word/document.xml", content: documentXml }
  ]);
}

export function createResumeExportArtifact(input: { draft: ResumeExportDraft; format: ResumeExportFormat }) {
  const filename = `${safeFilenamePart(input.draft.id)}.${input.format === "markdown" ? "md" : "docx"}`;
  const textContent = renderResumeMarkdown(input.draft);
  const bytes = input.format === "markdown" ? Buffer.from(textContent, "utf8") : renderResumeDocx(input.draft);
  return {
    format: input.format,
    filename,
    mimeType: input.format === "markdown" ? MARKDOWN_MIME_TYPE : DOCX_MIME_TYPE,
    bytes,
    textContent,
    checksum: createHash("sha256").update(bytes).digest("hex"),
    byteLength: bytes.length,
    warningText: DOCUMENT_EXPORT_WARNING_TEXT
  } satisfies ResumeExportArtifact;
}
