import type { DomainRuntimeDescriptor } from "@career-os/shared";

export const runtimeDescriptors: DomainRuntimeDescriptor[] = [
  {
    domainId: "system-kernel",
    displayName: "System Kernel Domain",
    managerId: "System Kernel Manager",
    commands: ["system.runtime_audit"],
    capabilities: ["RuntimeAuditCapability"],
    workers: ["RuntimeAuditWorker"],
    tools: ["RuntimeManifestInspectorTool"],
    eventsProduced: ["runtime.audit_started", "runtime.audit_completed", "runtime.audit_failed"],
    stateProjections: ["runtime.latest_audit"],
    approvalRequired: false,
    gated: false,
    disabled: false,
    uiVisible: true,
    tests: { unit: true, integration: false, e2e: false }
  },
  {
    domainId: "source-documents",
    displayName: "Source Documents Domain",
    managerId: "SourceDocumentsManager",
    commands: ["source_documents.import", "source_documents.list", "source_documents.extract_claims"],
    capabilities: ["SourceDocumentImportCapability", "CareerClaimExtractionCapability"],
    workers: ["SourceDocumentImportWorker", "CareerClaimExtractionWorker"],
    tools: ["PastedTextImportTool", "CareerClaimRegexExtractionTool"],
    eventsProduced: ["source_document.import_started", "source_document.imported", "source_document.import_failed", "source_document.claim_extraction_started", "source_document.claim_extracted", "source_document.claim_extraction_completed", "source_document.claim_extraction_failed"],
    stateProjections: ["source_documents.current", "career_claim.current"],
    approvalRequired: false,
    gated: false,
    disabled: false,
    uiVisible: true,
    tests: { unit: true, integration: false, e2e: false }
  },
  {
    domainId: "career-profile",
    displayName: "Career Profile Domain",
    managerId: "CareerProfileManager",
    commands: ["career_profile.generate", "career_profile.get"],
    capabilities: ["CareerProfileGenerationCapability"],
    workers: ["CareerProfileGenerationWorker"],
    tools: ["ProfileFactProjectionReaderTool", "CareerProfileSynthesisTool"],
    eventsProduced: ["career_profile.generation_started", "career_profile.generated", "career_profile.generation_failed", "career_profile.loaded"],
    stateProjections: ["career_profile.current"],
    stateProjectionDependencies: ["profile_facts.current"],
    dependencies: ["profile-facts", "profile_facts.current"],
    approvalRequired: false,
    gated: false,
    disabled: false,
    uiVisible: true,
    tests: { unit: true, integration: false, e2e: false }
  },
  {
    domainId: "career-opportunities",
    displayName: "Career Opportunities Domain",
    managerId: "CareerOpportunitiesManager",
    commands: ["career_opportunities.find_jobs", "career_opportunities.rank", "career_opportunities.create_packet", "career_opportunities.create_from_job_input"],
    capabilities: ["CareerOpportunityDiscoveryCapability", "CareerOpportunityManualImportCapability", "CareerOpportunityRankingCapability", "CareerOpportunityPacketCapability"],
    workers: ["CareerOpportunityDiscoveryWorker", "CareerOpportunityManualImportWorker", "CareerOpportunityRankingWorker", "CareerOpportunityPacketWorker"],
    tools: ["RemotiveApiTool", "ManualJobInputTool", "JobIntelligencePipelineTool", "ApplicationPacketAssemblyTool", "ResumeFactoryTool"],
    eventsProduced: ["career_opportunity.created", "career_opportunity.manual_import_started", "career_opportunity.manual_imported", "career_opportunity.manual_import_failed", "career_opportunity.scored", "career_opportunity.rejected", "career_opportunity.prioritized", "career_opportunity.status_updated", "career_opportunity.next_action_set", "career_opportunity.discovery_failed"],
    stateProjections: ["career_opportunities.current_pipeline"],
    stateProjectionDependencies: ["career_profile.current", "job.dashboard_segment"],
    dependencies: ["career-profile", "job-intelligence", "application-packet", "resume-factory", "profile-facts"],
    approvalRequired: false,
    gated: false,
    disabled: false,
    uiVisible: true,
    tests: { unit: true, integration: false, e2e: false }
  },
  {
    domainId: "job-discovery",
    displayName: "Job Discovery Domain",
    managerId: "Job Discovery Manager",
    commands: ["job_discovery.search"],
    capabilities: ["PublicJobSearchCapability"],
    workers: ["RemotiveJobSearchWorker"],
    tools: ["RemotiveApiTool"],
    eventsProduced: ["job.discovery_started", "job.discovery_completed", "job.discovery_failed"],
    stateProjections: ["job.discovery_run"],
    approvalRequired: false,
    gated: false,
    disabled: false,
    uiVisible: true,
    tests: { unit: false, integration: true, e2e: false }
  },
  {
    domainId: "job-intelligence",
    displayName: "Job Intelligence Domain",
    managerId: "Job Intelligence Manager",
    commands: ["jobs.run_pipeline"],
    capabilities: ["JobPipelineCapability"],
    workers: ["JobPipelineWorker"],
    tools: ["JobClassificationTool"],
    eventsProduced: ["job.pipeline_completed", "job.pipeline_failed"],
    stateProjections: ["job.dashboard_segment"],
    approvalRequired: false,
    gated: false,
    disabled: false,
    uiVisible: true,
    tests: { unit: true, integration: false, e2e: false }
  },
  {
    domainId: "application-packet",
    displayName: "Application Packet Domain",
    managerId: "Application Packet Manager",
    commands: ["application_packets.create", "application_packets.generate_placeholders", "application_packets.update_status"],
    capabilities: ["ApplicationPacketAssemblyCapability"],
    workers: ["ApplicationPacketWorker"],
    tools: ["PlaceholderGenerationTool"],
    eventsProduced: ["application_packet.created", "application_packet.updated", "application_packet.status_updated"],
    stateProjections: ["application_packet.current"],
    stateProjectionDependencies: ["career_opportunities.current_pipeline", "profile_facts.current", "resume.current_draft"],
    dependencies: ["career-opportunities", "resume-factory", "profile-facts"],
    approvalRequired: false,
    gated: false,
    disabled: false,
    uiVisible: true,
    tests: { unit: true, integration: false, e2e: false }
  },
  {
    domainId: "relationship-intelligence",
    displayName: "Relationship Intelligence Domain",
    managerId: "Relationship Intelligence Manager",
    commands: ["relationships.dedupe"],
    capabilities: ["RelationshipDedupeCapability"],
    workers: ["RelationshipDedupeWorker"],
    tools: ["RelationshipMatchingTool"],
    eventsProduced: ["relationship.deduplicated", "relationship.updated"],
    stateProjections: ["relationship.person"],
    approvalRequired: false,
    gated: false,
    disabled: false,
    uiVisible: true,
    tests: { unit: true, integration: false, e2e: false }
  },
  {
    domainId: "mission",
    displayName: "Mission Domain",
    managerId: "Mission Manager",
    commands: ["daily_mission.generate"],
    capabilities: ["DailyMissionGenerationCapability"],
    workers: ["DailyMissionWorker"],
    tools: ["MissionProjectionTool"],
    eventsProduced: ["daily_mission.generated"],
    stateProjections: ["daily_mission.current_queue"],
    stateProjectionDependencies: ["career_profile.current", "career_opportunities.current_pipeline", "application_packet.current", "resume.current_draft"],
    dependencies: ["career-profile", "career-opportunities", "application-packet", "resume-factory"],
    approvalRequired: false,
    gated: false,
    disabled: false,
    uiVisible: true,
    tests: { unit: true, integration: false, e2e: false }
  },
  {
    domainId: "resume-factory",
    displayName: "Resume Factory Domain",
    managerId: "Resume Factory Manager",
    commands: ["resume.generate", "resume.generate_placeholder"],
    capabilities: ["ResumeGenerationCapability"],
    workers: ["ProfileFactResolver", "ResumeClaimPolicy", "TechnicalResumeWorker", "TruthfulnessGuardWorker"],
    tools: ["ProfileFactProjectionReaderTool", "ResumeClaimPolicyTool", "TruthfulnessGuardTool"],
    eventsProduced: ["resume.profile_facts_loaded", "resume.claims_filtered", "resume.truthfulness_summary_created", "resume.claim_blocked", "resume.generated", "resume.generation_failed", "resume.placeholder_created"],
    stateProjections: ["resume.current_draft"],
    stateProjectionDependencies: ["profile_facts.current"],
    dependencies: ["profile_facts.current", "application-packet", "event-store", "state-store", "snapshot-store"],
    approvalRequired: false,
    gated: false,
    disabled: false,
    uiVisible: true,
    tests: { unit: false, integration: true, e2e: false }
  },
  {
    domainId: "document-export",
    displayName: "Document Export Domain",
    managerId: "Document Export Manager",
    commands: ["documents.export"],
    capabilities: ["LocalDocumentExportCapability"],
    workers: ["LocalMarkdownExportWorker"],
    tools: ["LocalMarkdownExportTool"],
    eventsProduced: ["document.local_exported"],
    stateProjections: ["document.local_export"],
    approvalRequired: false,
    gated: false,
    disabled: false,
    uiVisible: true,
    tests: { unit: false, integration: false, e2e: false }
  },
  {
    domainId: "profile-facts",
    displayName: "Profile Facts Domain",
    managerId: "ProfileFactsManager",
    commands: ["profile_facts.upsert", "profile_facts.list", "profile_facts.create_from_claims"],
    capabilities: ["UpsertProfileFactCapability", "ListProfileFactsCapability", "ClassifyClaimTruthStatusCapability", "CreateProfileFactsFromClaimsCapability"],
    workers: ["ProfileFactUpsertWorker", "ProfileFactListWorker", "ClaimTruthStatusWorker", "ProfileFactsFromClaimsWorker"],
    tools: ["ProfileFactNormalizationTool", "TruthUsagePolicyTool"],
    eventsProduced: [
      "profile_fact.upsert_started",
      "profile_fact.upserted",
      "profile_fact.rejected",
      "profile_fact.blocked",
      "profile_fact.truth_status_classified",
      "profile_fact.listed",
      "profile_facts.create_from_claims_started",
      "profile_fact.created_from_claim",
      "profile_facts.create_from_claims_completed",
      "profile_facts.create_from_claims_failed",
      "profile_fact.upsert_failed",
      "profile_fact.list_failed"
    ],
    stateProjections: ["profile_facts.current"],
    approvalRequired: false,
    gated: false,
    disabled: false,
    uiVisible: true,
    tests: { unit: true, integration: false, e2e: false }
  },
  {
    domainId: "communications",
    displayName: "Communications Domain",
    managerId: "Communications Manager",
    commands: ["email.send"],
    capabilities: ["ApprovedEmailReplayCapability"],
    workers: ["ApprovedEmailReplayWorker"],
    tools: ["NoExternalEmailTool"],
    eventsProduced: ["email.send.demo_replayed"],
    stateProjections: ["email.demo_replay"],
    approvalRequired: true,
    gated: true,
    disabled: false,
    uiVisible: true,
    tests: { unit: false, integration: false, e2e: false }
  }
];

export function getRuntimeDescriptor(domainId: string) {
  return runtimeDescriptors.find((descriptor) => descriptor.domainId === domainId);
}
